services:
  grafana:
    user: root
    container_name: 'mampersat-wopr-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/mampersat-wopr-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/mampersat-wopr-panel

    environment:
      NODE_ENV: development
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/dashboard.json
      GF_LOG_FILTERS: plugin.mampersat-wopr-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mampersat-wopr-panel
